# permissions for end users to edit chainlinknodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chainlinknode-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: chainlinknode-editor-role
rules:
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinknodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinknodes/status
  verbs:
  - get
