# permissions for end users to view chainlinkjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chainlinkjob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: chainlinkjob-viewer-role
rules:
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinkjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinkjobs/status
  verbs:
  - get
