---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinkjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinkjobs/finalizers
  verbs:
  - update
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinkjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinknodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinknodes/finalizers
  verbs:
  - update
- apiGroups:
  - oracle.example.com
  resources:
  - chainlinknodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
