---
apiVersion: v1
kind: Namespace
metadata:
  name: chainlink-oracle-nodes
  labels:
    name: chainlink-oracle-nodes
---
apiVersion: oracle.example.com/v1alpha1
kind: ChainlinkNode
metadata:
  name: chainlink-node-1
  namespace: chainlink-oracle-nodes
spec:
  foo: "We can set any custom fields to configure our deployments"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chainlink-node-1-config
  namespace: chainlink-oracle-nodes
data:
  config.toml: |
    [Log]
    Level = 'warn'

    [WebServer]
    AllowOrigins = '\*'
    SecureCookies = false

    [WebServer.TLS]
    HTTPSPort = 0

    [[EVM]]
    ChainID = '11155111'

    [[EVM.Nodes]]
    Name = 'Sepolia'
    WSURL = 'wss://sepolia.infura.io/ws/v3/9b61270ba20c4345945ecfb19c7f3cfd'
    HTTPURL = 'https://sepolia.infura.io/v3/9b61270ba20c4345945ecfb19c7f3cfd'
---
apiVersion: v1
kind: Secret
metadata:
  name: chainlink-node-1-secrets
  namespace: chainlink-oracle-nodes
data:
  secrets.toml: W1Bhc3N3b3JkXQpLZXlzdG9yZSA9ICdteXNlY3JldGtleXN0b3JlcGFzc3dvcmQnCltEYXRhYmFzZV0KVVJMID0gJ3Bvc3RncmVzcWw6Ly9wb3N0Z3JlczpteXNlY3JldHBhc3N3b3JkQGxvY2FsaG9zdDo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZScK
  # Content:
  #  [Password]
  #  Keystore = 'mysecretkeystorepassword'
  #  [Database]
  #  URL = 'postgresql://postgres:mysecretpassword@localhost:5432/postgres?sslmode=disable'

  apiuser.txt: dGVzdEBleGFtcGxlLmNvbQpteXNlY3JldHBhc3N3b3JkCg==
  # Content (for UI login):
  #  test@example.com
  #  mysecretpassword
